version: '3.1'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: BXa[tUNL94~/T5Ba)Ku^
      POSTGRES_DB: gRPCProxy
    ports:
      - 5432:5432